# Generated by Django 4.2.7 on 2025-10-24 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default=datetime.date(2025, 10, 25), verbose_name='تاريخ الكشف\t'),
        ),
    ]
