# Generated by Django 5.2.9 on 2025-12-20 11:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Account Approved'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default=datetime.date(2025, 12, 21), verbose_name='Appointment Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(choices=[('10-11', '10 AM - 11 AM'), ('11-12', '11 AM - 12 PM'), ('12-1', '12 PM - 1 PM'), ('4-5', '4 PM - 5 PM'), ('5-6', '5 PM - 6 PM'), ('6-7', '6 PM - 7 PM')], max_length=5, verbose_name='Appointment Time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.patient', verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(verbose_name='Department Description'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, choices=[('Consultant', 'Consultant'), ('Specialist', 'Specialist'), ('General Practitioner', 'General Practitioner')], default='Specialist', max_length=24, null=True, verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='Istanbul', max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='governorate',
            field=models.CharField(choices=[('Adana', 'Adana'), ('Ankara', 'Ankara'), ('Antalya', 'Antalya'), ('Aydın', 'Aydın'), ('Balıkesir', 'Balıkesir'), ('Bursa', 'Bursa'), ('Denizli', 'Denizli'), ('Diyarbakır', 'Diyarbakır'), ('Edirne', 'Edirne'), ('Eskişehir', 'Eskişehir'), ('Gaziantep', 'Gaziantep'), ('Hatay', 'Hatay'), ('Istanbul', 'Istanbul'), ('Izmir', 'Izmir'), ('Kayseri', 'Kayseri'), ('Kocaeli', 'Kocaeli'), ('Konya', 'Konya'), ('Malatya', 'Malatya'), ('Manisa', 'Manisa'), ('Mersin', 'Mersin'), ('Muğla', 'Muğla'), ('Sakarya', 'Sakarya'), ('Sivas', 'Sivas'), ('Samsun', 'Samsun'), ('Şanlıurfa', 'Şanlıurfa'), ('Tekirdağ', 'Tekirdağ'), ('Trabzon', 'Trabzon'), ('Van', 'Van')], default='Istanbul', max_length=100, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Medicine Name'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Available Quantity'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='shift_time',
            field=models.CharField(blank=True, choices=[('Morning Shift', 'Morning Shift'), ('Evening Shift', 'Evening Shift')], default='Morning Shift', max_length=20, null=True, verbose_name='Shift Time'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_doctor', to='master.doctor', verbose_name='Assigned Doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='admit_date',
            field=models.DateField(auto_now_add=True, verbose_name='Discharge Date'),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master.appointment', verbose_name='Medical Appointment'),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='doctor_fee',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Doctor Fee'),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='doctor_report',
            field=models.TextField(verbose_name='Doctor Report'),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='medicine_cost',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Medicine Cost'),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='other_charge',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Other Charges'),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='room_charge',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Room Charge'),
        ),
    ]
