# Generated by Django 5.2.9 on 2025-12-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_user_approved_at_user_approved_by_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change_required',
            field=models.BooleanField(default=False, verbose_name='Password Change Required'),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Temporary Password'),
        ),
    ]
